language: node_js
env:
  global:
    - secure: <YOUR_ENCRYPTED_DATA>
node_js:
- '0.10'
before_script:
- npm uninstall browser-sync --save-dev
script:
- node ./node_modules/gulp/bin/gulp build --release
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GIT_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/gulp/bin/gulp deploy
